platform :ios, '11.0'
use_frameworks!

target 'AuthPinScreen_Example' do
  pod 'AuthPinScreen', :path => '../'

  pod 'DesignKit', :path => '../../../Presentation/DesignKit'
  pod 'UIUtils', :path => '../../../Presentation/UIUtils'

  target "AuthPinScreenUITests" do
    use_frameworks!

    pod 'iOSSnapshotTestCase'
  end

end
