use_frameworks!
platform :ios, '8.0'

target 'AuthManager_Example' do
  pod 'AuthManager', :path => '../'

  pod 'Keychain', :path => '../../../Core/Keychain'

  target 'AuthManager_ExampleTests' do
    inherit! :search_paths

  end

end
