# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

podfiles = [
  './LocalPods/Core/FormattersKit/Example/Podfile',
  './LocalPods/Core/Keychain/Example/Podfile',
  './LocalPods/Services/FinnhubDataManager/Example/Podfile',
  './LocalPods/Screens/AuthPinScreen/Example/Podfile',
  './LocalPods/Services/AuthManager/Example/Podfile',
  './Podfile'
]

xcworkspaces = {
  'Formatters Kit' => './LocalPods/Core/FormattersKit/Example/FormattersKit.xcworkspace',
  'Keychain' => './LocalPods/Core/Keychain/Example/Keychain.xcworkspace',
  'Auth PIN Screen' => './LocalPods/Screens/AuthPinScreen/Example/AuthPinScreen.xcworkspace',
  'Auth Manager' => './LocalPods/Services/AuthManager/Example/AuthManager.xcworkspace',
  'Finnhub Data Managers' => './LocalPods/Services/FinnhubDataManager/Example/FinnhubDataManager.xcworkspace',
  'Tinkoff Investment' => './Tinkoff Investment.xcworkspace'
}

def run_pod_install(podfiles)

  podfiles.each do |podfile|
    cocoapods(
      podfile: podfile
    )
  end

end

def run_build(xcworkspaces)

  xcworkspaces.each do | project_name, xcworkspace |
    scan(
      skip_slack: true,
      build_for_testing: true,
      workspace: xcworkspace
    )
  end

end

def run_testing(xcworkspaces)
  
  xcworkspaces.each do | project_name, xcworkspace |
    scan(
      skip_build: true,
      workspace: xcworkspace,
      output_files: project_name + '.html'
    )
  end

end

default_platform(:ios)

platform :ios do

  desc "Установка зависимостей, сборка"
  lane :build_for_testing do
    run_pod_install(podfiles)
    run_build(xcworkspaces)
  end

  desc "Запуск тестов на уже скомпилированном приложении"
  lane :run_tests do
    run_testing(xcworkspaces)
  end

  desc "Сборка и тестирование"
  lane :build_and_test do
    build_for_testing
    run_tests
  end

end
