use_frameworks!
platform :ios, '13.0'

target 'NewsScreen_Example' do
  pod 'NewsScreen', :path => '../'

  pod 'Network', :path => '../../Network/'
  pod 'FormattersKit', :path => '../../FormattersKit/'
end
