use_frameworks!
platform :ios, '11.0'

target 'TicketList_Example' do
  pod 'TicketList', :path => '../'

  pod 'Storage', :path => '../../Storage/'
  pod 'Network', :path => '../../Network/'

  pod 'DesignKit', :path => '../../DesignKit/'
  pod 'UIUtils', :path => '../../UIUtils/'
end
