use_frameworks!
platform :ios, '11.0'

target 'TicketList_Example' do
  pod 'TicketList', :path => '../'

  pod 'Storage', :path => '../../Storage/'
  pod 'Network', :path => '../../Network/'
  pod 'UIViewKit', :path => '../../UIViewKit/'
end
