use_frameworks!
platform :ios, '10.0'

target 'FinnhubDataManager_Example' do
  pod 'FinnhubDataManager', :path => '../'

  pod 'Network', :path => '../../../Core/Network/'
  pod 'Storage', :path => '../../../Core/Storage/'

end
